# -*- coding: utf-8 -*-
"""Woneng Energy — structured site content (English B2B copy)."""

SITE = {
    "brand": "Woneng",
    "brand_full": "Zhaoqing Woneng High-Tech Co., Ltd.",
    "domain": "entelechyenergy.com",
    "base_url": "https://kkwen369.github.io/woneng-energy-website",
    "tagline": "Solar Lighting & Energy Storage — Factory Direct for Global B2B",
    "email": "sales@entelechyenergy.com",
    "whatsapp": "+8613920000000",
    "phone": "+86 139 2000 0000",
    "address": "Jinsheng Industrial Park, Jinli Town, Gaoyao District, Zhaoqing City, Guangdong, China",
    "established": "2023",
    "founded_note": "15 years of solar manufacturing & export experience",
    "fb": "",
}

NAV = [
    ("Home", "index.html"),
    ("About Us", "about.html"),
    ("Products", "products.html"),
    ("Solutions", "solutions.html"),
    ("Projects", "projects.html"),
    ("Factory", "factory.html"),
    ("Certifications", "certifications.html"),
    ("Contact", "contact.html"),
]

# Categories used for product index grouping
CATEGORIES = [
    ("Solar Lighting Series", "solar-lighting"),
    ("Solar Energy Storage Series", "solar-storage"),
    ("PV Supporting Accessories", "pv-accessories"),
]

PRODUCTS = [
    {
        "slug": "aio-solar-street-light",
        "name": "AIO Solar Street Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "All-in-one integrated solar street light with 10+ year service life.",
        "models": "S02 / S03 / S04 / S04 PRO / L08",
        "models_full": [
            "S02: BAT-AIO-4530P-S02, 8060P, 10080P, 120100P, 150120P, 180150P",
            "S03: BST-AIO-4030P-S03, 5140P, 6060P, 8080P, 100100P, 110120P",
            "S04 / S04 PRO: BST-AI0-2520P ~ 180180P (9 models)",
            "L08: BST-AIO-6000W / 7000W / 8000W-L08",
        ],
        "img": "images/products/aio-street-light.webp",
        "intro": "Fully integrated design — lamp body, battery, solar panel and smart controller in one unit. Tool-free installation, no complex wiring, IP65 protection for harsh outdoor climates. Built for municipal roads, rural electrification and overseas government lighting programs. Available in S02, S03, S04/S04 PRO and high-output L08 series with pole heights from 3m to 36m.",
        "advantages": [
            ("High-efficacy LEDs", "Seoul SMD3030 / SMD5040 chips, 200–220 lm/W, 100,000+ hour lifespan."),
            ("Long-life LiFePO4", "A-grade cells, 6000+ cycles, 10+ years life, 3-year full warranty."),
            ("Efficient panel", "A-grade monocrystalline, >21% efficiency, 25-year panel life."),
            ("Rugged housing", "6063 aluminium alloy + PC lens — corrosion & weather resistant."),
            ("Smart control", "Timing dimming, light sensing and motion modes, IP65."),
        ],
        "specs": [
            ("LED chips", "Seoul SMD3030 / SMD5040, 200–220 lm/W"),
            ("LED lifespan", ">100,000 hours"),
            ("Battery", "A-grade LiFePO4, 6000+ cycles, >10 years"),
            ("Solar panel", "Monocrystalline, >21% efficiency, 25-year life"),
            ("CCT / CRI", "2700–6500K / Ra>70"),
            ("Housing", "6063 aluminium + PC lens"),
            ("Protection", "IP65"),
            ("Backup time", "3–5 rainy nights"),
            ("Operating temp.", "-20°C ~ +60°C"),
            ("Pole height", "3m – 36m (by model)"),
            ("Warranty", "3 years full machine"),
        ],
        "applications": ["Municipal roads", "Rural roads", "Residential parks", "Industrial parks", "Government lighting projects"],
    },
    {
        "slug": "ait-solar-street-light",
        "name": "AIT Split Solar Street Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "Split flexible design for shaded or angled installation sites.",
        "models": "L03 / L04 / S03",
        "models_full": [
            "L03: BST-AIT-300W / 400W / 600W-L03",
            "L04: BST-AIT-100W / 200W / 300W / 400W-L04",
            "S03: BST-AIT-6030P ~ 240150P-S03 (5 models)",
        ],
        "img": "images/products/ait-street-light.webp",
        "intro": "Split design separates the panel from the lamp for sites with obstructions or special sun angles. Built-in power display, remote control, modular maintenance and stable operation from -20°C to +60°C with 2–5 rainy-day backup. L03/L04 are watt-class split lights; S03 is the pole-mounted integrated series.",
        "advantages": [
            ("Flexible split design", "Panel and lamp installed independently for difficult sites."),
            ("Power display", "Real-time remaining battery readout, remote control."),
            ("Modular build", "Battery, panel and lamp modules for easy service."),
            ("Wide temperature", "Stable -20°C ~ +60°C, 2–5 rainy-day backup."),
            ("Soft uniform light", "SMD3030 chips, CRI Ra > 70."),
        ],
        "specs": [
            ("LED", "High-brightness SMD3030, 200–220 lm/W, CRI Ra>70"),
            ("Battery", "LiFePO4, 6000+ cycles, >10 years"),
            ("Solar panel", "Class A+ monocrystalline, >25-year life"),
            ("CCT", "3000–6500K"),
            ("Backup", "3–5 rainy days (S03); 20–24h (L03/L04)"),
            ("Charge time", "4–6 hours (sunlight)"),
            ("Operating temp.", "-20°C ~ +60°C"),
            ("Control", "Light + motion + timer + remote"),
            ("Protection", "IP65"),
            ("Warranty", "3 years"),
        ],
        "applications": ["Mountain roads", "Courtyard lighting", "Scenic trails", "Outdoor factories", "Small–mid overseas lighting projects"],
    },
    {
        "slug": "solar-flood-light-f05",
        "name": "Solar Flood Light F05",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "High-power IP66 solar floodlight, 50W–400W.",
        "models": "50W / 100W / 200W / 300W / 400W",
        "models_full": [
            "BST-SFL-50W-F05", "BST-SFL-100W-F05", "BST-SFL-200W-F05",
            "BST-SFL-300W-F05", "BST-SFL-400W-F05",
        ],
        "img": "images/products/solar-flood-light.webp",
        "intro": "Professional outdoor high-power floodlight with IP66 waterproofing. Detachable housing for fast battery swap, built-in charge indicator, 120° wide beam for large-area coverage. Withstands rain, dust and intense sun. Five power classes from 50W to 400W (650–3800 lm).",
        "advantages": [
            ("IP66 waterproof", "Built for heavy rain, dust and intense sun."),
            ("+20% brightness", "Upgraded SMD3030 chips vs. conventional fixtures."),
            ("High-transmission lens", "PC lens improves light transmission 15–20%."),
            ("6000+ cycles", "3-year full warranty."),
            ("Wide 120° beam", "Large-area coverage, multi control modes."),
        ],
        "specs": [
            ("Power range", "50W – 400W (650–3800 lm)"),
            ("LED chips", "SMD3030, 600–828 pcs"),
            ("Battery", "LiFePO4 3.2V, 6000–42000 mAh, 6000 cycles"),
            ("Solar panel", "Monocrystalline 6V 12–50W"),
            ("Protection", "IP66"),
            ("Beam angle", "120°"),
            ("CCT", "3000–6500K"),
            ("Charge / light", "4–6h / 18–24h"),
            ("Working temp.", "-10°C ~ +65°C"),
            ("Warranty", "3 years"),
        ],
        "applications": ["Stadiums", "Squares", "Construction sites", "Warehouses", "Large outdoor areas"],
    },
    {
        "slug": "solar-garden-landscape-light",
        "name": "Solar Garden & Landscape Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "Decorative solar lighting for parks, paths and venues.",
        "models": "Garden / Landscape / Pathway / Stadium series",
        "models_full": [
            "Solar Garden Light", "Solar Landscape Light",
            "Solar Stadium Light: BST-SCL-200W / 400W / 600W / 800W",
        ],
        "img": "images/products/garden-light.webp",
        "intro": "Aesthetic solar garden and landscape fixtures for parks, scenic spots, campuses and pathways. Automatic dusk-to-dawn operation, wireless installation, enhancing outdoor ambience while cutting grid power use. Stadium-class models (BST-SCL) deliver 200–800W for large venues.",
        "advantages": [
            ("Auto operation", "Dusk-to-dawn sensor, zero wiring."),
            ("Decorative designs", "Garden, bollard, path and landscape styles."),
            ("Stadium option", "BST-SCL 200–800W for large venues."),
            ("Low maintenance", "Sealed, weatherproof construction."),
        ],
        "specs": [
            ("Operation", "Auto dusk-to-dawn"),
            ("Styles", "Garden / bollard / path / landscape / stadium"),
            ("LED", "SMD3030, 200–220 lm/W, Ra>70 (stadium)"),
            ("Battery", "LiFePO4, 6000 cycles (stadium)"),
            ("Protection", "IP65 / IP66 (stadium)"),
            ("Install", "Wireless, tool-light"),
        ],
        "applications": ["Parks", "Scenic spots", "Campuses", "Residential communities", "Pathways", "Stadiums & squares"],
    },
    {
        "slug": "light-poles-accessories",
        "name": "Light Poles & Accessories",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "3m–36m galvanized poles and mounting accessories.",
        "models": "3M / 6M / 8M / 10M / 12M … up to 36M",
        "models_full": [
            "Conical & polygonal steel poles",
            "Hoop / Straight Rod Double Arm / Curved Rod / Bent Rod Double Arm",
            "Custom height & colour on request",
        ],
        "img": "images/products/light-poles.webp",
        "intro": "Q235 steel poles formed by plasma cutting, bending and automatic welding (weld meets GB/T3323-1987 level 3, penetration >85%). Double-sided hot-dip galvanizing with zinc layer >85μm — 30-year anti-corrosion, 15-year anti-rust. Custom size and colour available, one-stop for street, garden, stadium and AC grid lighting projects.",
        "advantages": [
            ("Q235 steel", "Plasma-cut, welded, double-sided hot-dip galvanized."),
            ("Longevity", "30-year anti-corrosion, 15-year anti-rust."),
            ("Customizable", "Height 3–36m, size and colour on request."),
            ("Full range", "All mounting accessories & arm styles."),
        ],
        "specs": [
            ("Material", "Q235 low-carbon hot-rolled steel"),
            ("Process", "Plasma cutting + auto welding, GB/T3323-1987 L3"),
            ("Galvanizing", "Double-sided hot-dip, zinc >85μm"),
            ("Height", "3M – 36M"),
            ("Anti-corrosion", "30 years"),
            ("Anti-rust", "15 years"),
            ("Surface", "Powder coated, custom colour"),
        ],
        "applications": ["Street lighting", "Garden lighting", "Stadium lighting", "AC grid lighting", "Turnkey projects"],
    },
    {
        "slug": "portable-energy-storage",
        "name": "Portable Energy Storage",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "300W–1000W portable power station, EU & US versions.",
        "models": "300W / 500W / 1000W (EU & US)",
        "models_full": [
            "EU: BST-SAL-300W-EU / 500W-EU / 1000W-EU",
            "US: BST-SAL-300W-US / 500W-US / 1000W-US",
        ],
        "img": "images/products/portable-storage.webp",
        "intro": "Integrated metal-housing power station with solar & grid dual charging and pure sine wave output. UPS function (<50ms switch), <50dB silent operation, ideal for camping, home backup and RV/marine use. EU (220–240V) and US (100–120V) versions with LiFePO4 650–2000Wh capacity.",
        "advantages": [
            ("Dual charging", "Solar (12–60V) & grid, pure sine wave output."),
            ("UPS function", "Switch delay < 50ms, seamless backup."),
            ("Silent", "Operation noise < 50dB."),
            ("10000+ cycles", "USB 2.0 + Type-C PD20W, AC / DC outputs."),
            ("Metal housing", "Safe, rugged, global-spec compliant."),
        ],
        "specs": [
            ("Power", "300W / 500W / 1000W"),
            ("Battery", "LiFePO4 650 / 1000 / 2000 Wh, ≥10000 cycles"),
            ("Versions", "EU 220–240V / US 100–120V, 60Hz"),
            ("Charging", "Solar 12–60V (250–550W) + AC grid"),
            ("Output", "Pure sine wave, >86% inverter eff."),
            ("UPS switch", "< 50ms (EPS)"),
            ("Ports", "AC / USB 2.0 / Type-C PD20W"),
            ("Noise", "< 50dB"),
            ("Temp.", "-10°C ~ +40°C"),
        ],
        "applications": ["Outdoor camping", "Home emergency", "RV & marine", "Field work", "Small appliances", "Car & yacht"],
    },
    {
        "slug": "solar-power-generator",
        "name": "Solar Power Generator",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "1200W–6200W all-in-one solar generator, EU/US.",
        "models": "1200W / 1500W / 3000W / 3600W / 6000W / 6200W",
        "models_full": [
            "EU: BST-SPSS-1500W / 3000W / 6200W",
            "US: BST-SPSS-1200W-U / 3600W-U / 6000W-U",
        ],
        "img": "images/products/solar-generator.webp",
        "intro": "All-in-one unit with built-in inverter, controller and LiFePO4 battery. MPPT solar charging to full in 3–5 hours, pure sine wave, multi-protection and parallel expansion for off-grid regions. EU (120–500Vdc MPPT) and US (15–300Vdc MPPT) versions from 1.2kW to 6.2kW.",
        "advantages": [
            ("All-in-one", "Inverter + controller + battery."),
            ("Fast charge", "MPPT, full in 3–5 hours."),
            ("Pure sine wave", "Safe for sensitive electronics."),
            ("Expandable", "Parallel units for more power."),
            ("Dual versions", "EU / US, 1.2kW–6.2kW."),
        ],
        "specs": [
            ("Power", "1200W – 6200W"),
            ("Battery", "LiFePO4, 10yr life, >6000 cycles"),
            ("Charge", "MPPT, 3–5h full"),
            ("MPPT range", "EU 120–500Vdc / US 15–300Vdc"),
            ("Output", "Pure sine wave, 220V AC / USB / 12V / TYPE-C"),
            ("Transfer", "10ms (PC) / 20ms (appliances)"),
            ("Protection", "Overload / overvoltage / low-voltage / over-temp"),
        ],
        "applications": ["Off-grid homes", "Outdoor events", "Backup power", "Remote sites", "Weak-grid areas", "Car & yacht"],
    },
    {
        "slug": "solar-hybrid-inverter",
        "name": "Solar Hybrid Inverter",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "1.5kW–125kW hybrid inverter, EU/US single & three phase.",
        "models": "1.5kW / 3.3kW / 6.5kW / 12kW … up to 125kW",
        "models_full": [
            "EU LV: BST-HPL-1500W / 3300W / 6500W / 12000W",
            "EU HV: BST-HPG-6200W / 12000W-B",
            "US Split: BST-HPG-3600W-U / 7200W-S / 12000W-S",
            "EU 3-Phase HV: BST-HPI-30/40/50/60KW-H3",
            "US 3-Phase HV: BST-HPC-30/60KW-H3U",
        ],
        "img": "images/products/hybrid-inverter.webp",
        "intro": "Built-in MPPT, seamless grid/off-grid switching, up to 98.7% efficiency and 10ms transfer. Remote monitoring for residential and commercial PV storage. Covers single-phase low/high-voltage (EU & US split-phase) and three-phase high-voltage 30–125kW for C&I and utility-scale projects. IP66 models available for outdoor install.",
        "advantages": [
            ("High efficiency", "Up to 98.7% conversion (PV→INV)."),
            ("Seamless switch", "Grid/off-grid, 10ms transfer."),
            ("MPPT tracking", "Multi-MPPT, high-voltage battery ready."),
            ("Outdoor ready", "IP66 on high-voltage three-phase models."),
            ("Full range", "1.5kW – 125kW, EU/US, 1/3 phase."),
        ],
        "specs": [
            ("Power", "1.5kW – 125kW"),
            ("Efficiency", "Up to 98.7% (PV→INV)"),
            ("Switch", "10ms grid/off-grid"),
            ("MPPT", "30–500V / 60–500V / 180–1000V (by model)"),
            ("Battery", "12V / 24V / 48V / 160–1000V HV"),
            ("Protection", "IP66 (HV 3-phase) / indoor models"),
            ("Monitoring", "RS485 / RS232 / WiFi / GPRS"),
        ],
        "applications": ["Residential PV", "Commercial PV", "Hybrid systems", "Off-grid", "Micro-grids", "C&I & utility"],
    },
    {
        "slug": "powerwall-energy-storage-battery",
        "name": "Powerwall Energy Storage Battery",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "Wall-mounted 5.12kWh–17.92kWh home & small C&I storage.",
        "models": "PWBA series: 5.12 / 10.25 / 15.36 / 17.92 kWh",
        "models_full": [
            "BST-PWBA24200 (5.12kWh, 25.6V)",
            "BST-PWBA48100 (5.12kWh, 51.2V)",
            "BST-PWBA48200 (10.25kWh)",
            "BST-PWBA48300 (15.36kWh)",
            "BST-PWBA48350 (17.92kWh)",
            "PWBH series 5–30kWh",
        ],
        "img": "images/products/powerwall-battery.webp",
        "intro": "Minimalist wall-mounted units with brand-new Gotion cells, smart BMS, 6000+ cycles @ 80% DOD and 10+ year life. RS485 / CAN / RS232 comms, up to 15 units in parallel for virtually unlimited capacity. Built for home and small commercial backup with the PWBA series (5.12–17.92kWh) and the higher-capacity PWBH series.",
        "advantages": [
            ("Gotion cells", "Reliable, long-life LiFePO4."),
            ("6000+ cycles", "@ 80% DOD, 10+ year life."),
            ("Smart BMS", "RS485 / CAN / RS232."),
            ("Expandable", "Up to 15 units in parallel."),
            ("Compact", "Wall-mount, space-saving."),
        ],
        "specs": [
            ("Capacity", "5.12kWh – 17.92kWh (PWBA); 5–30kWh (PWBH)"),
            ("Cells", "Gotion LiFePO4, brand-new A-grade"),
            ("Cycles", "6000+ @ 80% DOD, 25°C"),
            ("Life", "10+ years"),
            ("Comms", "RS485 / CAN / RS232"),
            ("Max current", "200A charge/discharge (PWBA)"),
            ("Protection", "IP21, 0–60°C"),
        ],
        "applications": ["Home storage", "Small C&I backup", "Solar self-consumption", "Peak shaving", "Remote homes"],
    },
    {
        "slug": "rack-mounted-high-voltage-battery",
        "name": "Rack-mounted High Voltage Battery",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "25kWh–184kWh modular rack battery for C&I.",
        "models": "25kWh / 50kWh / 100kWh / 184kWh",
        "models_full": [
            "Modular high-voltage rack / cabinet",
            "Outdoor High-Voltage Battery Cabinet (IP54)",
            "Parallel expansion for project scale",
        ],
        "img": "images/products/rack-battery.webp",
        "intro": "Modular rack/cabinet high-voltage storage with intelligent temperature control, stable 0–50°C operation and comprehensive electrical protection. Standardized cabinets for medium–small commercial and industrial plants. Outdoor high-voltage cabinet version available with IP54 rated enclosure.",
        "advantages": [
            ("Modular racks", "Parallel expansion."),
            ("Smart cooling", "Stable 0–50°C operation."),
            ("Full protection", "Anti short / over-charge / over-discharge."),
            ("Standard cabinet", "Easy plant integration."),
        ],
        "specs": [
            ("Capacity", "25kWh – 184kWh"),
            ("Type", "High-voltage rack / outdoor cabinet"),
            ("Temp. range", "0°C – 50°C"),
            ("Enclosure", "IP54 (outdoor cabinet)"),
            ("Design", "Modular rack / cabinet"),
            ("Use", "Medium–small C&I"),
        ],
        "applications": ["Commercial plants", "Industrial sites", "C&I storage", "Peak-valley arbitrage", "Backup power"],
    },
    {
        "slug": "industrial-commercial-bess",
        "name": "Industrial & Commercial BESS System",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "500kW / 1000kW container energy storage system.",
        "models": "500kW / 1000kW container (20ft / 40ft)",
        "models_full": [
            "20-Foot Container BESS",
            "40-Foot Container BESS",
            "500kW / 1000kW PCS, multi-mode",
        ],
        "img": "images/products/bess-system.webp",
        "intro": "Industrial-grade container BESS with IP54 protection, intelligent fire suppression, thermal management and remote monitoring. Multi-mode (PV / generator / grid), peak-valley arbitrage, emergency backup and off-grid supply. Available in 20-foot and 40-foot container formats at 500kW and 1000kW.",
        "advantages": [
            ("Container system", "500kW / 1000kW, IP54."),
            ("Smart safety", "Auto fire suppression, lightning protection."),
            ("Wide climate", "Air cooling, -25°C ~ +60°C."),
            ("Multi-mode", "PV / generator / grid compatible."),
            ("Remote O&M", "Monitoring & control platform."),
        ],
        "specs": [
            ("Power", "500kW / 1000kW"),
            ("Format", "20ft / 40ft container"),
            ("Protection", "IP54 industrial"),
            ("Safety", "Auto fire + lightning protection"),
            ("Temp.", "-25°C ~ +60°C"),
            ("Modes", "PV / generator / grid / off-grid"),
        ],
        "applications": ["Large factories", "Industrial parks", "PV power stations", "Peak-valley arbitrage", "Emergency backup"],
    },
    {
        "slug": "pv-supporting-accessories",
        "name": "PV Supporting Accessories",
        "cat": "pv-accessories",
        "cat_name": "PV Supporting Accessories",
        "tagline": "Panels, pumps, mounts, cables and combiner boxes.",
        "models": "590W–720W panels & full accessory set",
        "models_full": [
            "590W–720W monocrystalline panels",
            "Solar-powered water pump",
            "Mounting brackets / PV cables / combiner boxes / pump controllers",
        ],
        "img": "images/products/pv-accessories.webp",
        "intro": "Complete matching range — 590W–720W high-efficiency monocrystalline panels, solar water pumps, mounting brackets, PV cables, combiner boxes and pump controllers. One-stop customized PV + storage solutions that pair with every Woneng system.",
        "advantages": [
            ("High-efficiency panels", "590W–720W monocrystalline."),
            ("Solar water pump", "Direct PV-powered pumping."),
            ("Full accessory set", "Pumps, mounts, cables, combiners."),
            ("One-stop", "Customized PV + storage packages."),
            ("Compatible", "Matches all Woneng systems."),
        ],
        "specs": [
            ("Panels", "590W – 720W monocrystalline"),
            ("Pump", "Solar-powered water pump"),
            ("Includes", "Brackets, cables, combiners, pump controllers"),
            ("Service", "One-stop customized"),
        ],
        "applications": ["PV systems", "Water pumping", "Mounting structures", "Wiring", "Turnkey projects"],
    },
]

SOLUTIONS = [
    {
        "slug": "africa-offgrid-solar-storage",
        "title": "Africa Off-grid Solar & Energy Storage Solution",
        "img": "images/projects/nigeria.webp",
        "lead": "Reliable power where the grid is weak or absent — engineered for African climate and demand.",
        "points": [
            "Hybrid PV + LiFePO4 storage for homes, villages and businesses",
            "High-temperature & dust resistant design for harsh environments",
            "Stable supply through outages and unstable low-voltage grids",
            "Scalable from single household to community micro-grid",
        ],
    },
    {
        "slug": "municipal-road-solar-lighting",
        "title": "Municipal Road Solar Lighting Project Solution",
        "img": "images/projects/sri-lanka.webp",
        "lead": "Turnkey solar street lighting for cities, towns and rural roads.",
        "points": [
            "AIO & split solar street lights with 3-year warranty",
            "Galvanized poles 3m–36m, custom height & colour",
            "Intelligent dimming & motion control for energy saving",
            "Proven in overseas government lighting programs",
        ],
    },
    {
        "slug": "residential-pv-storage",
        "title": "Residential PV + Energy Storage Solution",
        "img": "images/projects/indonesia.webp",
        "lead": "Self-generation and backup power for homes and remote residences.",
        "points": [
            "Powerwall & portable units for daily + emergency use",
            "Hybrid inverter with seamless grid/off-grid switching",
            "Reduce bills, gain energy independence",
            "Easy install, mobile monitoring",
        ],
    },
    {
        "slug": "industrial-commercial-storage",
        "title": "Industrial & Commercial Energy Storage Solution",
        "img": "images/projects/malaysia.webp",
        "lead": "Cut peak demand costs and secure supply for factories and parks.",
        "points": [
            "Rack & container BESS for peak-valley arbitrage",
            "500kW–1000kW container systems, IP54, smart safety",
            "Stable power for production lines and equipment",
            "Remote monitoring & O&M platform",
        ],
    },
    {
        "slug": "outdoor-large-area-lighting",
        "title": "Outdoor & Large-area Lighting Solution",
        "img": "images/projects/dubai.webp",
        "lead": "High-power solar flood and area lighting for big spaces.",
        "points": [
            "Solar Flood Light F05, 50W–400W, IP66",
            "Stadiums, squares, construction, warehouses",
            "120° wide beam, multi control modes",
            "No grid connection required",
        ],
    },
    {
        "slug": "nigeria-local-offgrid",
        "title": "Nigeria Local Off-grid Solar Energy Solution",
        "img": "images/projects/nigeria.webp",
        "lead": "Built for Nigeria's off-grid reality — heat, dust and unstable supply.",
        "points": [
            "Heat & dust resistant, low-voltage grid tolerant",
            "Local delivery experience across Nigerian states",
            "Home, business and community packages",
            "WhatsApp-fast local inquiry & support",
        ],
    },
    {
        "slug": "africa-rural-solar-lighting",
        "title": "Africa Rural Solar Lighting & Power Supply Solution",
        "img": "images/projects/zambia.webp",
        "lead": "Bring light and power to rural African communities.",
        "points": [
            "Rural road & village solar lighting",
            "Solar home systems & community storage",
            "Durable, low-maintenance for remote areas",
            "Supported by overseas warehouse logistics",
        ],
    },
]

PROJECTS = [
    {
        "country": "Nigeria", "title": "Lagos & Abuja Solar Street Lighting Program",
        "img": "images/projects/nigeria.webp",
        "desc": "Large-scale AIO solar street light deployment across Lagos and Abuja roads and estates, improving night safety and cutting grid dependence. Local off-grid expertise applied to heat- and dust-prone sites.",
        "scope": ["1,500+ AIO street lights", "Municipal & estate roads", "Local logistics support"],
    },
    {
        "country": "Zambia", "title": "Zambia Rural Electrification Project",
        "img": "images/projects/zambia.webp",
        "desc": "Solar home systems and street lighting delivered to rural Zambian communities, extending reliable power to off-grid villages with long-life LiFePO4 storage.",
        "scope": ["Rural village lighting", "Solar home systems", "Community storage"],
    },
    {
        "country": "Sri Lanka", "title": "Sri Lanka Municipal Lighting Upgrade",
        "img": "images/projects/sri-lanka.webp",
        "desc": "Municipal road and park solar lighting upgrade using split and AIO street lights, with galvanized poles and intelligent dimming for energy savings.",
        "scope": ["Municipal roads", "Parks & pathways", "Smart dimming"],
    },
    {
        "country": "Dubai, UAE", "title": "Dubai Commercial Solar Storage",
        "img": "images/projects/dubai.webp",
        "desc": "Commercial solar power generators and hybrid inverters supplied for Dubai facilities, with pure sine wave output for sensitive equipment and extreme-heat tolerance.",
        "scope": ["Commercial backup", "Hybrid inverters", "High-temp operation"],
    },
    {
        "country": "Indonesia", "title": "Indonesia Island Micro-grid",
        "img": "images/projects/indonesia.webp",
        "desc": "Island community micro-grid combining PV panels, hybrid inverters and rack batteries to deliver stable 24/7 power to remote Indonesian islands.",
        "scope": ["Island micro-grid", "Rack battery storage", "PV + inverter"],
    },
    {
        "country": "Malaysia", "title": "Malaysia Industrial & Generator Supply",
        "img": "images/projects/malaysia.webp",
        "desc": "Solar power generators and portable storage delivered to Malaysian industrial and outdoor clients, with parallel expansion for higher loads.",
        "scope": ["Industrial backup", "Portable storage", "Parallel expansion"],
    },
]

CERTS = [
    ("ISO 9001", "Quality Management System", "Certified standardized production & quality control."),
    ("ISO 14001", "Environmental Management", "Compliant environmental management system."),
    ("ISO 45001", "Occupational Health & Safety", "Certified occupational health & safety management."),
    ("IATF 16949", "Automotive Quality Management", "Automotive-grade quality management system."),
    ("ISO 13485", "Medical Device Quality", "Quality management for medical-device manufacturing."),
    ("CE", "European Conformity", "Meets EU safety, health & environmental standards."),
    ("RoHS", "Restriction of Hazardous Substances", "Restricts hazardous substances in electronics."),
    ("IEC", "International Electrotechnical", "Compliance with IEC international standards."),
    ("MSDS", "Material Safety Data Sheet", "Battery material safety documentation."),
    ("UN38.3", "Battery Transport Safety", "Safe air/sea transport certification for batteries."),
    ("OEM / ODM", "Custom Manufacturing", "Private-label & engineering customization service."),
]

STATS = [
    ("15+", "Years solar manufacturing & export"),
    ("50,000", "Batteries produced annually"),
    ("60+", "Countries & regions served"),
    ("3yr", "Full-machine warranty"),
]
