# -*- coding: utf-8 -*-
"""Woneng Energy — structured site content (English B2B copy)."""

SITE = {
    "brand": "Woneng",
    "brand_full": "Zhaoqing Woneng High-Tech Co., Ltd.",
    "domain": "entelechyenergy.com",
    "tagline": "Solar Lighting & Energy Storage — Factory Direct for Global B2B",
    "email": "sales@entelechyenergy.com",
    "whatsapp": "+8613920000000",
    "phone": "+86 139 2000 0000",
    "address": "Jinsheng Industrial Park, Jinli Town, Gaoyao District, Zhaoqing City, Guangdong, China",
    "established": "2023",
    " founded_note": "15 years of solar manufacturing & export experience",
    "fb": "",
}

NAV = [
    ("Home", "index.html"),
    ("About Us", "about.html"),
    ("Products", "products.html"),
    ("Solutions", "solutions.html"),
    ("Projects", "projects.html"),
    ("Factory", "factory.html"),
    ("Certifications", "certifications.html"),
    ("Contact", "contact.html"),
]

# Categories used for product index grouping
CATEGORIES = [
    ("Solar Lighting Series", "solar-lighting"),
    ("Solar Energy Storage Series", "solar-storage"),
    ("PV Supporting Accessories", "pv-accessories"),
]

PRODUCTS = [
    {
        "slug": "aio-solar-street-light",
        "name": "AIO Solar Street Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "All-in-one integrated solar street light with 10+ year service life.",
        "models": "S02 / S03 / S04 / S04 PRO / L08",
        "img": "images/products/aio-street-light.webp",
        "intro": "Fully integrated design — lamp body, battery, solar panel and smart controller in one unit. Tool-free installation, no complex wiring, IP65 protection for harsh outdoor climates. Built for municipal roads, rural electrification and overseas government lighting programs.",
        "advantages": [
            ("High-efficacy LEDs", "Seoul SMD3030/5040 chips, 200–220 lm/W, 100,000+ hour lifespan."),
            ("Long-life LiFePO4", "A-grade cells, 6000+ cycles, 10+ years life, 3-year full warranty."),
            ("Efficient panel", "A-grade monocrystalline, >21% efficiency, 25-year panel life."),
            ("Rugged housing", "6063 aluminium alloy — corrosion & weather resistant."),
            ("Smart control", "Timing dimming, light sensing and motion modes."),
        ],
        "specs": [
            ("Light output", "Up to 200–220 lm/W"),
            ("Battery", "A-grade LiFePO4, 6000+ cycles"),
            ("Solar panel", "Monocrystalline, >21% efficiency"),
            ("Housing", "6063 aluminium alloy"),
            ("Protection", "IP65"),
            ("Warranty", "3 years full machine"),
        ],
        "applications": ["Municipal roads", "Rural roads", "Residential parks", "Industrial parks", "Government lighting projects"],
    },
    {
        "slug": "ait-solar-street-light",
        "name": "AIT Split Solar Street Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "Split flexible design for shaded or angled installation sites.",
        "models": "L03 / L04 / S03",
        "img": "images/products/ait-street-light.webp",
        "intro": "Split design separates the panel from the lamp for sites with obstructions or special sun angles. Built-in power display, remote control, modular maintenance and stable operation from -20°C to +60°C with 2–5 rainy-day backup.",
        "advantages": [
            ("Flexible split design", "Panel and lamp installed independently for difficult sites."),
            ("Power display", "Real-time remaining battery readout, remote control."),
            ("Modular build", "Battery, panel and lamp modules for easy service."),
            ("Wide temperature", "Stable -20°C ~ +60°C, 2–5 rainy-day backup."),
            ("Soft uniform light", "SMD3030 chips, CRI Ra > 70."),
        ],
        "specs": [
            ("LED", "High-brightness SMD3030, CRI Ra > 70"),
            ("Backup", "2–5 rainy days"),
            ("Operating temp.", "-20°C ~ +60°C"),
            ("Control", "Light + motion + timer + remote"),
            ("Construction", "Modular, tool-friendly service"),
        ],
        "applications": ["Mountain roads", "Courtyard lighting", "Scenic trails", "Outdoor factories", "Small–mid overseas lighting projects"],
    },
    {
        "slug": "solar-flood-light-f05",
        "name": "Solar Flood Light F05",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "High-power IP66 solar floodlight, 50W–400W.",
        "models": "50W / 100W / 200W / 300W / 400W",
        "img": "images/products/solar-flood-light.webp",
        "intro": "Professional outdoor high-power floodlight with IP66 waterproofing. Detachable housing for fast battery swap, built-in charge indicator, 120° wide beam for large-area coverage. Withstands rain, dust and intense sun.",
        "advantages": [
            ("IP66 waterproof", "Built for heavy rain, dust and intense sun."),
            ("+20% brightness", "Upgraded SMD3030 chips vs. conventional fixtures."),
            ("High-transmission lens", "PC lens improves light transmission 15–20%."),
            ("6000+ cycles", "3-year full warranty."),
            ("Wide 120° beam", "Large-area coverage, multi control modes."),
        ],
        "specs": [
            ("Power range", "50W – 400W"),
            ("Protection", "IP66"),
            ("Beam angle", "120°"),
            ("Battery cycles", "6000+"),
            ("Warranty", "3 years"),
        ],
        "applications": ["Stadiums", "Squares", "Construction sites", "Warehouses", "Large outdoor areas"],
    },
    {
        "slug": "solar-garden-landscape-light",
        "name": "Solar Garden & Landscape Light",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "Decorative solar lighting for parks, paths and venues.",
        "models": "Garden / Landscape / Pathway series",
        "img": "images/products/garden-light.webp",
        "intro": "Aesthetic solar garden and landscape fixtures for parks, scenic spots, campuses and pathways. Automatic dusk-to-dawn operation, wireless installation, enhancing outdoor ambience while cutting grid power use.",
        "advantages": [
            ("Auto operation", "Dusk-to-dawn sensor, zero wiring."),
            ("Decorative designs", "Garden, bollard, path and landscape styles."),
            ("Wireless install", "No trenching or grid connection."),
            ("Low maintenance", "Sealed, weatherproof construction."),
        ],
        "specs": [
            ("Operation", "Auto dusk-to-dawn"),
            ("Styles", "Garden / bollard / path / landscape"),
            ("Install", "Wireless, tool-light"),
            ("Use", "Parks, campuses, pathways"),
        ],
        "applications": ["Parks", "Scenic spots", "Campuses", "Residential communities", "Pathways"],
    },
    {
        "slug": "light-poles-accessories",
        "name": "Light Poles & Accessories",
        "cat": "solar-lighting",
        "cat_name": "Solar Lighting Series",
        "tagline": "4m–12m galvanized poles and mounting accessories.",
        "models": "4M / 6M / 8M / 10M / 12M",
        "img": "images/products/light-poles.webp",
        "intro": "Q235 steel poles with double-sided hot-dip galvanizing — 30-year anti-corrosion, 15-year anti-rust. Custom size and colour available, one-stop for street, garden, stadium and AC grid lighting projects.",
        "advantages": [
            ("Q235 steel", "Double-sided hot-dip galvanized."),
            ("Longevity", "30-year anti-corrosion, 15-year anti-rust."),
            ("Customizable", "Size and colour on request."),
            ("Full range", "4m–12m, all mounting accessories."),
        ],
        "specs": [
            ("Material", "Q235 steel, hot-dip galvanized"),
            ("Height", "4M – 12M"),
            ("Anti-corrosion", "30 years"),
            ("Anti-rust", "15 years"),
        ],
        "applications": ["Street lighting", "Garden lighting", "Stadium lighting", "AC grid lighting", "Turnkey projects"],
    },
    {
        "slug": "portable-energy-storage",
        "name": "Portable Energy Storage",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "300W–1000W portable power station, EU & US versions.",
        "models": "300W / 500W / 700W / 1000W",
        "img": "images/products/portable-storage.webp",
        "intro": "Integrated metal-housing power station with solar & grid dual charging and pure sine wave output. UPS function (<50ms switch), <50dB silent operation, ideal for camping, home backup and RV/marine use.",
        "advantages": [
            ("Dual charging", "Solar & grid, pure sine wave output."),
            ("UPS function", "Switch delay < 50ms, seamless backup."),
            ("Silent", "Operation noise < 50dB."),
            ("10000+ cycles", "PD20W, USB / AC / DC outputs."),
        ],
        "specs": [
            ("Power", "300W – 1000W"),
            ("Versions", "EU & US"),
            ("Charging", "Solar + grid dual"),
            ("UPS switch", "< 50ms"),
            ("Cycles", "10000+"),
        ],
        "applications": ["Outdoor camping", "Home emergency", "RV & marine", "Field work", "Small appliances"],
    },
    {
        "slug": "solar-power-generator",
        "name": "Solar Power Generator",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "1200W–6200W all-in-one solar generator, EU/US.",
        "models": "1200W / 2400W / 3600W / 5000W / 6200W",
        "img": "images/products/solar-generator.webp",
        "intro": "All-in-one unit with built-in inverter, controller and LiFePO4 battery. MPPT solar charging to full in 3–5 hours, pure sine wave, multi-protection and parallel expansion for off-grid regions.",
        "advantages": [
            ("All-in-one", "Inverter + controller + battery."),
            ("Fast charge", "MPPT, full in 3–5 hours."),
            ("Pure sine wave", "Safe for sensitive electronics."),
            ("Expandable", "Parallel units for more power."),
            ("Dual versions", "EU / US, 1200W–6200W."),
        ],
        "specs": [
            ("Power", "1200W – 6200W"),
            ("Charge", "MPPT, 3–5h full"),
            ("Output", "Pure sine wave"),
            ("Expansion", "Parallel capable"),
        ],
        "applications": ["Off-grid homes", "Outdoor events", "Backup power", "Remote sites", "Weak-grid areas"],
    },
    {
        "slug": "solar-hybrid-inverter",
        "name": "Solar Hybrid Inverter",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "1.5kW–125kW hybrid inverter, EU/US single & three phase.",
        "models": "1.5kW / 3kW / 5kW / 10kW / 50kW / 125kW",
        "img": "images/products/hybrid-inverter.webp",
        "intro": "Built-in MPPT, seamless grid/off-grid switching, up to 98.7% efficiency, 10ms transfer, IP66 for outdoor install. Remote monitoring for residential and commercial PV storage systems.",
        "advantages": [
            ("High efficiency", "Up to 98.7% conversion."),
            ("Seamless switch", "Grid/off-grid, 10ms transfer."),
            ("MPPT tracking", "Multi-MPPT, high-voltage battery ready."),
            ("Outdoor ready", "IP66, remote monitoring."),
            ("Full range", "1.5kW – 125kW, EU/US."),
        ],
        "specs": [
            ("Power", "1.5kW – 125kW"),
            ("Efficiency", "Up to 98.7%"),
            ("Switch", "10ms grid/off-grid"),
            ("Protection", "IP66"),
            ("Monitoring", "Remote (app / PC)"),
        ],
        "applications": ["Residential PV", "Commercial PV", "Hybrid systems", "Off-grid", "Micro-grids"],
    },
    {
        "slug": "powerwall-energy-storage-battery",
        "name": "Powerwall Energy Storage Battery",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "Wall-mounted 2.5kWh–30kWh home & small C&I storage.",
        "models": "PWBA / PWBH series",
        "img": "images/products/powerwall-battery.webp",
        "intro": "Minimalist wall-mounted units with Gotion cells, smart BMS, 6000+ cycles @ 80% DOD and 10+ year life. Bluetooth / RS485 / CAN comms, supports parallel expansion for home and small commercial backup.",
        "advantages": [
            ("Gotion cells", "Reliable, long-life LiFePO4."),
            ("6000+ cycles", "@ 80% DOD, 10+ year life."),
            ("Smart BMS", "Bluetooth / RS485 / CAN."),
            ("Expandable", "Multi-unit series/parallel."),
            ("Compact", "Wall-mount, space-saving."),
        ],
        "specs": [
            ("Capacity", "2.5kWh – 30kWh"),
            ("Series", "PWBA / PWBH"),
            ("Cycles", "6000+ @ 80% DOD"),
            ("Life", "10+ years"),
            ("Comms", "Bluetooth / RS485 / CAN"),
        ],
        "applications": ["Home storage", "Small C&I backup", "Solar self-consumption", "Peak shaving", "Remote homes"],
    },
    {
        "slug": "rack-mounted-high-voltage-battery",
        "name": "Rack-mounted High Voltage Battery",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "25kWh–184kWh modular rack battery for C&I.",
        "models": "25kWh / 50kWh / 100kWh / 184kWh",
        "img": "images/products/rack-battery.webp",
        "intro": "Modular rack/cabinet high-voltage storage with intelligent temperature control, stable 0–50°C operation and comprehensive electrical protection. Standardized cabinets for medium–small commercial and industrial plants.",
        "advantages": [
            ("Modular racks", "Parallel expansion."),
            ("Smart cooling", "Stable 0–50°C operation."),
            ("Full protection", "Anti short / over-charge / over-discharge."),
            ("Standard cabinet", "Easy plant integration."),
        ],
        "specs": [
            ("Capacity", "25kWh – 184kWh"),
            ("Temp. range", "0°C – 50°C"),
            ("Design", "Modular rack / cabinet"),
            ("Use", "Medium–small C&I"),
        ],
        "applications": ["Commercial plants", "Industrial sites", "C&I storage", "Peak-valley arbitrage", "Backup power"],
    },
    {
        "slug": "industrial-commercial-bess",
        "name": "Industrial & Commercial BESS System",
        "cat": "solar-storage",
        "cat_name": "Solar Energy Storage Series",
        "tagline": "500kW / 1000kW container energy storage system.",
        "models": "500kW / 1000kW container",
        "img": "images/products/bess-system.webp",
        "intro": "Industrial-grade container BESS with IP54 protection, intelligent fire suppression, thermal management and remote monitoring. Multi-mode (PV / generator / grid), peak-valley arbitrage, emergency backup and off-grid supply.",
        "advantages": [
            ("Container system", "500kW / 1000kW, IP54."),
            ("Smart safety", "Auto fire suppression, lightning protection."),
            ("Wide climate", "Air cooling, -25°C ~ +60°C."),
            ("Multi-mode", "PV / generator / grid compatible."),
            ("Remote O&M", "Monitoring & control platform."),
        ],
        "specs": [
            ("Power", "500kW / 1000kW"),
            ("Protection", "IP54 industrial"),
            ("Safety", "Auto fire + lightning protection"),
            ("Temp.", "-25°C ~ +60°C"),
            ("Modes", "PV / generator / grid / off-grid"),
        ],
        "applications": ["Large factories", "Industrial parks", "PV power stations", "Peak-valley arbitrage", "Emergency backup"],
    },
    {
        "slug": "pv-supporting-accessories",
        "name": "PV Supporting Accessories",
        "cat": "pv-accessories",
        "cat_name": "PV Supporting Accessories",
        "tagline": "Panels, pumps, mounts, cables and combiner boxes.",
        "models": "590W–720W panels & full accessory set",
        "img": "images/products/pv-accessories.webp",
        "intro": "Complete matching range — 590W–720W high-efficiency monocrystalline panels, solar water pumps, mounting brackets, PV cables, combiner boxes and pump controllers. One-stop customized PV + storage solutions.",
        "advantages": [
            ("High-efficiency panels", "590W–720W monocrystalline."),
            ("Full accessory set", "Pumps, mounts, cables, combiners."),
            ("One-stop", "Customized PV + storage packages."),
            ("Compatible", "Matches all Woneng systems."),
        ],
        "specs": [
            ("Panels", "590W – 720W monocrystalline"),
            ("Includes", "Pumps, brackets, cables, combiners"),
            ("Service", "One-stop customized"),
        ],
        "applications": ["PV systems", "Water pumping", "Mounting structures", "Wiring", "Turnkey projects"],
    },
]

SOLUTIONS = [
    {
        "slug": "africa-offgrid-solar-storage",
        "title": "Africa Off-grid Solar & Energy Storage Solution",
        "img": "images/projects/nigeria.webp",
        "lead": "Reliable power where the grid is weak or absent — engineered for African climate and demand.",
        "points": [
            "Hybrid PV + LiFePO4 storage for homes, villages and businesses",
            "High-temperature & dust resistant design for harsh environments",
            "Stable supply through outages and unstable low-voltage grids",
            "Scalable from single household to community micro-grid",
        ],
    },
    {
        "slug": "municipal-road-solar-lighting",
        "title": "Municipal Road Solar Lighting Project Solution",
        "img": "images/projects/sri-lanka.webp",
        "lead": "Turnkey solar street lighting for cities, towns and rural roads.",
        "points": [
            "AIO & split solar street lights with 3-year warranty",
            "Galvanized poles 4m–12m, custom height & colour",
            "Intelligent dimming & motion control for energy saving",
            "Proven in overseas government lighting programs",
        ],
    },
    {
        "slug": "residential-pv-storage",
        "title": "Residential PV + Energy Storage Solution",
        "img": "images/projects/indonesia.webp",
        "lead": "Self-generation and backup power for homes and remote residences.",
        "points": [
            "Powerwall & portable units for daily + emergency use",
            "Hybrid inverter with seamless grid/off-grid switching",
            "Reduce bills, gain energy independence",
            "Easy install, mobile monitoring",
        ],
    },
    {
        "slug": "industrial-commercial-storage",
        "title": "Industrial & Commercial Energy Storage Solution",
        "img": "images/projects/malaysia.webp",
        "lead": "Cut peak demand costs and secure supply for factories and parks.",
        "points": [
            "Rack & container BESS for peak-valley arbitrage",
            "500kW–1000kW container systems, IP54, smart safety",
            "Stable power for production lines and equipment",
            "Remote monitoring & O&M platform",
        ],
    },
    {
        "slug": "outdoor-large-area-lighting",
        "title": "Outdoor & Large-area Lighting Solution",
        "img": "images/projects/dubai.webp",
        "lead": "High-power solar flood and area lighting for big spaces.",
        "points": [
            "Solar Flood Light F05, 50W–400W, IP66",
            "Stadiums, squares, construction, warehouses",
            "120° wide beam, multi control modes",
            "No grid connection required",
        ],
    },
    {
        "slug": "nigeria-local-offgrid",
        "title": "Nigeria Local Off-grid Solar Energy Solution",
        "img": "images/projects/nigeria.webp",
        "lead": "Built for Nigeria's off-grid reality — heat, dust and unstable supply.",
        "points": [
            "Heat & dust resistant, low-voltage grid tolerant",
            "Local delivery experience across Nigerian states",
            "Home, business and community packages",
            "WhatsApp-fast local inquiry & support",
        ],
    },
    {
        "slug": "africa-rural-solar-lighting",
        "title": "Africa Rural Solar Lighting & Power Supply Solution",
        "img": "images/projects/zambia.webp",
        "lead": "Bring light and power to rural African communities.",
        "points": [
            "Rural road & village solar lighting",
            "Solar home systems & community storage",
            "Durable, low-maintenance for remote areas",
            "Supported by overseas warehouse logistics",
        ],
    },
]

PROJECTS = [
    {
        "country": "Nigeria", "title": "Lagos & Abuja Solar Street Lighting Program",
        "img": "images/projects/nigeria.webp",
        "desc": "Large-scale AIO solar street light deployment across Lagos and Abuja roads and estates, improving night safety and cutting grid dependence. Local off-grid expertise applied to heat- and dust-prone sites.",
        "scope": ["1,500+ AIO street lights", "Municipal & estate roads", "Local logistics support"],
    },
    {
        "country": "Zambia", "title": "Zambia Rural Electrification Project",
        "img": "images/projects/zambia.webp",
        "desc": "Solar home systems and street lighting delivered to rural Zambian communities, extending reliable power to off-grid villages with long-life LiFePO4 storage.",
        "scope": ["Rural village lighting", "Solar home systems", "Community storage"],
    },
    {
        "country": "Sri Lanka", "title": "Sri Lanka Municipal Lighting Upgrade",
        "img": "images/projects/sri-lanka.webp",
        "desc": "Municipal road and park solar lighting upgrade using split and AIO street lights, with galvanized poles and intelligent dimming for energy savings.",
        "scope": ["Municipal roads", "Parks & pathways", "Smart dimming"],
    },
    {
        "country": "Dubai, UAE", "title": "Dubai Commercial Solar Storage",
        "img": "images/projects/dubai.webp",
        "desc": "Commercial solar power generators and hybrid inverters supplied for Dubai facilities, with pure sine wave output for sensitive equipment and extreme-heat tolerance.",
        "scope": ["Commercial backup", "Hybrid inverters", "High-temp operation"],
    },
    {
        "country": "Indonesia", "title": "Indonesia Island Micro-grid",
        "img": "images/projects/indonesia.webp",
        "desc": "Island community micro-grid combining PV panels, hybrid inverters and rack batteries to deliver stable 24/7 power to remote Indonesian islands.",
        "scope": ["Island micro-grid", "Rack battery storage", "PV + inverter"],
    },
    {
        "country": "Malaysia", "title": "Malaysia Industrial & Generator Supply",
        "img": "images/projects/malaysia.webp",
        "desc": "Solar power generators and portable storage delivered to Malaysian industrial and outdoor clients, with parallel expansion for higher loads.",
        "scope": ["Industrial backup", "Portable storage", "Parallel expansion"],
    },
]

CERTS = [
    ("ISO 9001", "Quality Management System", "Certified standardized production & quality control."),
    ("ISO 14001", "Environmental Management", "Compliant environmental management system."),
    ("CE", "European Conformity", "Meets EU safety, health & environmental standards."),
    ("RoHS", "Restriction of Hazardous Substances", "Restricts hazardous substances in electronics."),
    ("IEC", "International Electrotechnical", "Compliance with IEC international standards."),
    ("MSDS", "Material Safety Data Sheet", "Battery material safety documentation."),
    ("UN38.3", "Battery Transport Safety", "Safe air/sea transport certification for batteries."),
    ("OEM / ODM", "Custom Manufacturing", "Private-label & engineering customization service."),
]

STATS = [
    ("15+", "Years solar manufacturing & export"),
    ("50,000", "Batteries produced annually"),
    ("60+", "Countries & regions served"),
    ("3yr", "Full-machine warranty"),
]
